from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class Evidence:

    """
    A single piece of evidence supporting
    a RISF metric.
    """

    title: str

    description: str

    source: str

    confidence: float = 1.0

    paper_title: str | None = None

    paper_id: str | None = None

    url: str | None = None

    metadata: dict[str, Any] = field(default_factory=dict)


class EvidenceCollector:

    """
    Collects evidence generated by
    different modules.
    """

    def __init__(self):

        self.items: list[Evidence] = []

    # --------------------------------------------------

    def add(

        self,

        title: str,

        description: str,

        source: str,

        confidence: float = 1.0,

        paper_title: str | None = None,

        paper_id: str | None = None,

        url: str | None = None,

        metadata: dict | None = None,

    ):

        self.items.append(

            Evidence(

                title=title,

                description=description,

                source=source,

                confidence=confidence,

                paper_title=paper_title,

                paper_id=paper_id,

                url=url,

                metadata=metadata or {},

            )

        )

    # --------------------------------------------------

    def extend(

        self,

        evidence: list[Evidence],

    ):

        self.items.extend(evidence)

    # --------------------------------------------------

    def deduplicate(self):

        unique = {}

        for item in self.items:

            key = (

                item.title.strip().lower(),

                item.paper_title,

            )

            if key not in unique:

                unique[key] = item

                continue

            if item.confidence > unique[key].confidence:

                unique[key] = item

        self.items = list(unique.values())

    # --------------------------------------------------

    def sort(self):

        self.items.sort(

            key=lambda x: x.confidence,

            reverse=True,

        )

    # --------------------------------------------------

    def top(

        self,

        k: int = 10,

    ) -> list[Evidence]:

        self.sort()

        return self.items[:k]

    # --------------------------------------------------

    def clear(self):

        self.items.clear()